
# Source: flightctl/templates/flightctl-rabbitmq-statefulset.yaml
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-rabbitmq-auth
  namespace: open-cluster-management
type: Opaque
data:
  password: cGFzc3dvcmQ=
