
# Source: flightctl/templates/flightctl-rabbitmq-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flightctl-rabbitmq
  namespace: open-cluster-management
  labels:
    flightctl.service: flightctl-rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: management
  selector:
    flightctl.service: flightctl-rabbitmq
