
# Source: flightctl/templates/flightctl-periodic-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flightctl-periodic-config
  namespace: open-cluster-management
data:
  config.yaml: |-
    database:
        hostname: flightctl-db.open-cluster-management.svc.cluster.local
        type: pgsql
        port: 5432
        name: flightctl
        user: admin
        password: adminpass   # we should funnel this via secrets instead
    service: {}
    queue:
        amqpUrl: amqp://user:password@flightctl-rabbitmq.open-cluster-management.svc.cluster.local:5672/
