
# Source: flightctl/templates/flightctl-kv-statefulset.yaml
# StatefulSet for Redis
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flightctl-kv
  namespace: open-cluster-management
  labels:
    flightctl.service: flightctl-kv
spec:
  serviceName: flightctl-kv
  replicas: 1
  selector:
    matchLabels:
      flightctl.service: flightctl-kv
  template:
    metadata:
      labels:
        flightctl.service: flightctl-kv
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: flightctl-kv
          image: docker.io/redis:7.4.1
          imagePullPolicy: Always
          ports:
            - name: kv
              containerPort: 6379
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flightctl-kv-secret
                  key: REDIS_PASSWORD
          command:
            - "redis-server"
            - "/etc/redis/redis.conf"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          volumeMounts:
            - name: flightctl-kv-data
              mountPath: /var/lib/redis/data
            - name: flightctl-kv-config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
          resources:
            requests:
              cpu: "1000m"
              memory: "2Gi"
      volumes:
        - name: flightctl-kv-config
          configMap:
            name: flightctl-kv-config
            defaultMode: 0644
  volumeClaimTemplates:
    - metadata:
        name: flightctl-kv-data
        annotations:
          kubernetes.io/reclaimPolicy: Delete
      spec:
        storageClassName: 
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
