
# Source: flightctl/templates/flightctl-kv-statefulset.yaml
# Secret to store the Redis password
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-kv-secret
  namespace: open-cluster-management
type: Opaque
data:
  REDIS_PASSWORD: YWRtaW5wYXNz
