apiVersion: v1
kind: ConfigMap
metadata:
  name: acm-dr-virt-config
  namespace: open-cluster-management-backup
data:

  ###### Configuration for the acm-dr-virt-install policy ###
  ########################################################

  # backupNS is the ns where velero/oadp is installed on the cluster
  backupNS: open-cluster-management-backup
  channel: stable-1.4
  # credentials_hub_secret_name is the name of the Secret resource used by the OADP DPA resource to connect to the storage location
  # hub-secret must be a Secret available under the acm-virt-config namespace. It will be copied over to the backup cluster by the policy
  credentials_hub_secret_name: "cloud-credentials"
  credentials_name: "cloud-credentials"
  dpa_name: dpa-hub-policy
  dpa_spec: "{
  \"backupLocations\": [
    {
      \"velero\": {
        \"config\": {
          \"profile\": \"default\",
          \"region\": \"us-east-1-change-me\"
        },
        \"credential\": {
          \"key\": \"cloud\",
          \"name\": \"cloud-credentials\"
        },
        \"default\": true,
        \"objectStorage\": {
          \"bucket\": \"velero-bucket-change-me\",
          \"prefix\": \"velero-prefix-change-me\"
        },
        \"provider\": \"aws\"
      }
    }
  ],
  \"configuration\": {
    \"nodeAgent\": {
      \"enable\": true,
      \"uploaderType\": \"kopia\"
    },
    \"velero\": {
      \"defaultPlugins\": [
        \"csi\",       
        \"openshift\",
        \"kubevirt\",
        \"aws\"
      ],
    }
  },
}"
  ##### end configuration for the acm-dr-virt-install policy##

  ###### Configuration for the acm-dr-virt-backup policy ###
  ########################################################
  scheduleTTL: 120h
  # define the schedules to be used by the vm backup; schedule_hub_config_name is the name of the configmap defining all the 
  # supported cron job definitions
  # you should define a ConfigMap named schedule-cron and set values such as : daily_8am: 0 8 * * *
  schedule_hub_config_name: "acm-dr-virt-schedule-cron"
  ##### end configuration for the acm-dr-virt-backup policy##

  ###### Configuration for the acm-dr-virt-restore policy ###
  ########################################################
  ## restore_hub_config_name is the name of the ConfigMap defining the restore information
  ## The user should create on the hub a ConfigMap with the name defined below
  ## if this is not a restore operation, set the restoreName in the configName to emmpty 
  restore_hub_config_name: "acm-dr-virt-restore-config"
  ##### end configuration for the acm-dr-virt-restore policy##
