apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: acm-dr-virt-placement
  namespace: open-cluster-management-backup
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'acm-virt-config'
              operator: 'Exists'    
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists

