# Copyright Contributors to the Open Cluster Management project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.org }}:cluster-backup-chart:clusterrole
  labels:
    app: cluster-backup-chart
    chart: cluster-backup-chart
    release: cluster-backup-chart
    heritage: Helm
    app.kubernetes.io/instance: cluster-backup-chart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cluster-backup-chart
    helm.sh/chart: cluster-backup-chart
    component: clusterrole

rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
