apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  name: acm-hub-backup
  namespace: open-cluster-management-backup
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - local-cluster
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: is-hub
              operator: In
              values:
                - 'true'  