# Copyright Contributors to the Open Cluster Management project
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  labels:
    app: cluster-backup-chart
    chart: cluster-backup-chart
    release: cluster-backup-chart
    heritage: Helm
    app.kubernetes.io/instance: cluster-backup-chart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clusster-backup-chart
    helm.sh/chart: cluster-backup-chart
    velero.io/exclude-from-backup: "true"
    component: policy
  annotations:
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-4 Backups of information are conducted maintained and tested
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/source: system
  name: backup-restore-enabled
  namespace: open-cluster-management-backup
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-backup-pod-running
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  labels:
                    app: cluster-backup-chart
                  namespace: open-cluster-management-backup
                status:
                  phase: Running
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: oadp-pod-running
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  annotations:
                    repository: https://github.com/openshift/oadp-operator
                  namespace: open-cluster-management-backup
                status:
                  phase: Running
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: velero-pod-running
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  labels:
                    app.kubernetes.io/name: velero
                  namespace: open-cluster-management-backup
                status:
                  phase: Running
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: data-protection-application-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: oadp.openshift.io/v1alpha1
                kind: DataProtectionApplication
                metadata:
                  namespace: open-cluster-management-backup
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: backup-storage-location-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: BackupStorageLocation
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: Available
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: backup-schedule-cron-enabled
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  labels:
                    velero.io/schedule-name: acm-validation-policy-schedule
                  namespace: open-cluster-management-backup
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-managed-clusters-schedule-backups-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: open-cluster-management-backup
                  labels:
                    velero.io/schedule-name: acm-managed-clusters-schedule
                status:
                  phase: Completed
          remediationAction: inform
          severity: high 
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-resources-schedule-backups-available
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: open-cluster-management-backup
                  labels:
                    velero.io/schedule-name: acm-resources-schedule
                status:
                  phase: Completed
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-backup-in-progress-report
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Backup
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: InProgress                                                            
          remediationAction: inform
          severity: medium
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-backup-clusters-collision-report
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: BackupSchedule
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: BackupCollision                                                           
          remediationAction: inform
          severity: high   
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acm-backup-phase-validation
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: BackupSchedule
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: FailedValidation 
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: BackupSchedule
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: Failed 
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: BackupSchedule
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: ""
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Restore
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: ""
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1beta1
                kind: Restore
                metadata:
                  namespace: open-cluster-management-backup
                status:
                  phase: Error                                                       
          remediationAction: inform
          severity: high                                                                        
  remediationAction: inform
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  name: backup-restore-enabled
  namespace: open-cluster-management-backup
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: backup-restore-enabled
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: backup-restore-enabled
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  name: backup-restore-enabled
  namespace: open-cluster-management-backup
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster
