apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  name: acm-managed-hub-backup
  namespace: open-cluster-management-backup
spec:
  description: This PolicySet is used to place Hub backup policies on any managed cluster where ACM Hub has been installed. These managed clusters must have the is-hub=true label. 
  policies:
    - backup-restore-enabled
    - backup-restore-auto-import
    - backup-restore-oadp