apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.128.0.87"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2024-01-18T16:46:16Z"
  generateName: insights-metrics-5748688c8c-
  labels:
    app: policyreport
    chart: policyreport-2.3.0
    component: insights-metrics
    heritage: release-service
    ocm-antiaffinity-selector: insightsmetrics
    pod-template-hash: 5748688c8c
    release: policyreport
  name: insights-metrics-5748688c8c-75w29
  namespace: open-cluster-management
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: insights-metrics-5748688c8c
    uid: 38eaa565-d4b0-47cc-8dba-d55afbe963c8
  resourceVersion: "1657692"
  uid: 8f3be33b-e989-4e32-9b9a-0b92a5d29778
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
            - ppc64le
            - s390x
            - arm64
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: ocm-antiaffinity-selector
              operator: In
              values:
              - insightsclient
          topologyKey: topology.kubernetes.io/zone
        weight: 70
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: ocm-antiaffinity-selector
              operator: In
              values:
              - insightsclient
          topologyKey: kubernetes.io/hostname
        weight: 35
  containers:
  - args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8383/
    - --logtostderr=true
    - --v=6
    - --tls-cert-file=/var/run/insights-metrics-certs/tls.crt
    - --tls-private-key-file=/var/run/insights-metrics-certs/tls.key
    - --tls-min-version=VersionTLS12
    image: registry.redhat.io/rhacm2/kube-rbac-proxy-rhel8@sha256:eb13f6fa0768104e940701c50914d0d1b049177f75ab2dd98abf123468e08958
    imagePullPolicy: IfNotPresent
    name: kube-rbac-proxy
    ports:
    - containerPort: 8443
      name: https
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsUser: 1000680000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/insights-metrics-certs
      name: certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ttp4w
      readOnly: true
  - args:
    - --port=8383
    - --host=127.0.0.1
    - --telemetry-port=8444
    image: registry.redhat.io/rhacm2/insights-metrics-rhel8@sha256:a47915cdef6103ffdb28135158aa11322ec55c96fa64e7d9e668baf79eac6dd6
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8444
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    name: metrics
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8444
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 25m
        memory: 32Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000680000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/insights-metrics-certs
      name: certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ttp4w
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: insights-client-dockercfg-b2v2k
  nodeName: ip-10-0-14-128.us-east-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000680000
    runAsNonRoot: true
    seLinuxOptions:
      level: s0:c26,c15
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: insights-client
  serviceAccountName: insights-client
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: certs
    secret:
      defaultMode: 420
      secretName: insights-metrics-certs
  - name: kube-api-access-ttp4w
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-18T16:46:16Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T15:35:38Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T15:35:38Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-18T16:46:16Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://a769ffc79a9f1301f10b2f979bc24b15ab048fb370c22069370db486c31e0028
    image: registry.redhat.io/rhacm2/kube-rbac-proxy-rhel8@sha256:eb13f6fa0768104e940701c50914d0d1b049177f75ab2dd98abf123468e08958
    imageID: registry.redhat.io/rhacm2/kube-rbac-proxy-rhel8@sha256:eb13f6fa0768104e940701c50914d0d1b049177f75ab2dd98abf123468e08958
    lastState: {}
    name: kube-rbac-proxy
    ready: true
    restartCount: 5
    started: true
    state:
      running:
        startedAt: "2024-01-31T15:35:21Z"
  - containerID: cri-o://2679abdd2a4768861f253d476cba16cad91c6c3c96dd7b253b63146fcc9a0a41
    image: registry.redhat.io/rhacm2/insights-metrics-rhel8@sha256:a47915cdef6103ffdb28135158aa11322ec55c96fa64e7d9e668baf79eac6dd6
    imageID: registry.redhat.io/rhacm2/insights-metrics-rhel8@sha256:4b16536fc494b7a57dbb3f4c20ed0c5421f32ec6474a8c6a0d17c68f4762f3dc
    lastState: {}
    name: metrics
    ready: true
    restartCount: 5
    started: true
    state:
      running:
        startedAt: "2024-01-31T15:35:22Z"
  hostIP: 10.0.14.128
  phase: Running
  podIP: 10.128.0.87
  podIPs:
  - ip: 10.128.0.87
  qosClass: Burstable
  startTime: "2024-01-18T16:46:16Z"