apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: kui-web-terminal
  namespace: default
spec:
  channel: charts-v1 
  name: kui-web-terminal
  placement:
    local: true
  packageOverrides:
    - packageName: kui-web-terminal
      packageAlias: kui
      packageOverrides:
      - path: spec.values
        value: |
          global:
            imageTagPostfix: "{{POSTFIX}}"
          proxy:
            image:
              repository: "{{IMAGEREPO}}"
              name: "kui-web-terminal"
              tag: 3.5.0
            clusterIP: "icp-management-ingress"
            clusterPort: "{{ router_https_port }}"
            clusterDomain: "{{ cluster_CA_domain }}"