apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ .Values.org }}:{{ .Chart.Name }}:multicluster-operators'
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
