apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ .Values.org }}:{{ .Chart.Name }}:multicluster-applications'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ .Values.org }}:{{ .Chart.Name }}:multicluster-applications'
subjects:
- kind: ServiceAccount
  name: multicluster-applications
  namespace: '{{ .Values.global.namespace }}'
