apiVersion: v1
kind: Service
metadata:
  labels:
    app: console-chart-v2
    chart: "console-chart-{{ .Values.hubconfig.hubVersion }}"
    component: console
    subcomponent: acm-cli-downloads
    release: console
    app.kubernetes.io/instance: console
    app.kubernetes.io/name: console-chart
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: acm-cli-cert
  name: acm-cli-downloads
spec:
  ports:
    - name: https-8443
      port: 443
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    subcomponent: acm-cli-downloads
