apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: console-chart-v2
    chart: "console-chart-{{ .Values.hubconfig.hubVersion }}"
    component: console
    subcomponent: acm-cli-downloads
    release: console
    app.kubernetes.io/instance: console
    app.kubernetes.io/name: console-chart
  name: acm-cli-downloads
  namespace: "{{ .Values.global.namespace }}"
spec:
  host: "acm-cli-downloads.{{ .Values.hubconfig.ocpIngress }}"
  port:
    targetPort: https-8443
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: acm-cli-downloads
  wildcardPolicy: None
