# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-chart
  labels:
    app: console-chart
    chart: console-chart-{{ .Values.hubconfig.hubVersion }}
    release: console
    app.kubernetes.io/instance: console
    app.kubernetes.io/name: console-chart
    component: serviceaccount
