# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config
  labels:
    app: console
    component: "console"
    chart: console-chart-{{ .Values.hubconfig.hubVersion }}
    release: console-chart
data:
  LOG_LEVEL: info
  ansibleIntegration: disabled
  singleNodeOpenshift: disabled
  