# Copyright Contributors to the Open Cluster Management project

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:console:aggregate-userpreferences
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
rules:
  - apiGroups: ['console.open-cluster-management.io']
    resources: ['userpreferences']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'delete', 'patch']
