# Copyright Contributors to the Open Cluster Management project

apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  annotations:
    installer.open-cluster-management.io/release-version: 2.12.0
  labels:
    installer.name: multiclusterhub
    installer.namespace: { { .Values.global.namespace } }
  name: acm
spec:
  backend:
    service:
      basePath: /plugin/
      name: console-chart-console-v2
      namespace: { { .Values.global.namespace } }
      port: 3000
    type: Service
  displayName: Red Hat Advanced Cluster Management
  proxy:
    - alias: console
      authorization: UserToken
      endpoint:
        service:
          name: console-chart-console-v2
          namespace: { { .Values.global.namespace } }
          port: 3000
        type: Service
