kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-metrics-monitor
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - services
      - endpoints
