# Copyright (c) 2020 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.open-cluster-management.io/auth-type: access-token
    ingress.open-cluster-management.io/secure-backends: "true"
    kubernetes.io/ingress.class: ingress-open-cluster-management
  name: console-chart-console-v2
  labels:
    app: console-chart-v2
    chart: console-chart-{{ .Values.hubconfig.hubVersion }}
    release: console
    app.kubernetes.io/instance: console
    app.kubernetes.io/name: console-chart
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: console-chart-console-v2
            port:
              number: 3000
        path: /multicloud
        pathType: ImplementationSpecific
      - backend:
          service:
            name: console-chart-console-v2
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
