# Copyright Contributors to the Open Cluster Management project
{{- if include "dynamicPlugins.supported" . }}
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: acm
  annotations:
    console.openshift.io/use-i18n: "true"
spec:
  displayName: Red Hat Advanced Cluster Management
  proxy:
    - type: Service
      alias: console
      service:
        name: {{ .Values.fullname }}-console-v2
        namespace: {{ .Release.Namespace }}
        port: 3000
      authorize: true
  service:
    basePath: /plugin/
    name: {{ .Values.fullname }}-console-v2
    namespace: {{ .Release.Namespace }}
    port: 3000
{{ end }}