apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ .Values.org }}:{{ .Chart.Name }}:submariner-addon'
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - ''
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - namespaces
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - bind
  - escalate
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - get
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - customresourcedefinitions/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - submariner.io
  resources:
  - brokers
  verbs:
  - create
  - get
  - update
  - delete
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclustersets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - config.openshift.io
  resources:
  - apiservers
  - infrastructures
  - infrastructures/status
  verbs:
  - get
- apiGroups:
  - submarineraddon.open-cluster-management.io
  resources:
  - submarinerconfigs
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - submarineraddon.open-cluster-management.io
  resources:
  - submarinerconfigs/status
  verbs:
  - update
  - patch
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - addondeploymentconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - clustermanagementaddons
  verbs:
  - create
  - get
  - list
  - watch
  - update
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - clustermanagementaddons/finalizers
  verbs:
  - update
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - clustermanagementaddons/status
  verbs:
  - patch
  - update
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - delete
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons/finalizers
  verbs:
  - update
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons/status
  verbs:
  - patch
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update
  - patch
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/kube-apiserver-client
  resources:
  - signers
  verbs:
  - approve
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
