apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ .Values.org }}:{{ .Chart.Name }}:submariner-addon'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ .Values.org }}:{{ .Chart.Name }}:submariner-addon'
subjects:
- kind: ServiceAccount
  name: submariner-addon
  namespace: '{{ .Values.global.namespace }}'
