
# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ""
subjects:
- kind: ServiceAccount
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Values.global.namespace }}"