apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
spec:
  additionalCertificateAuthorities:
    - name: letsencrypt-ca
  failedProvisionConfig:
    skipGatherLogs: true
  globalPullSecret:
    name: private-secret