apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: mongodb-sub
spec:
  channel: charts-v1
  name: multicloud-mongodb
  placement:
    local: true 
  packageOverrides:
    - packageName: multicloud-mongodb
      packageOverrides:
      - path: spec.values
        value: |
          imageTagPostfix: "{{SUFFIX}}"
          imagePullSecrets:
          - "{{PULLSECRET}}"
          network_ip_version: ipv4
          auth:
            enabled: true
            existingAdminSecret: mongodb-admin
          image:
            pullPolicy: "{{PULLPOLICY}}"
            repository: {{IMAGEREPO}}
          installImage:
            pullPolicy: "{{PULLPOLICY}}"
            repository: {{IMAGEREPO}}
          persistentVolume:
            accessModes:
            - ReadWriteOnce
            enabled: true
            size: 20Gi
            storageClass: {{STORAGECLASS}}
          replicas: "1"
          tls:
            casecret: multicloud-ca-cert
            enabled: true
