apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mongodb-sub
spec:
  channel: charts-v1
  name: multicluster-mongodb
  placement:
    local: true 
  packageOverrides:
    - packageName: multicluster-mongodb
      packageOverrides:
      - path: spec
        value: 
          imageTagPostfix: "{{SUFFIX}}"
          imagePullSecrets:
          - "{{PULLSECRET}}"
          network_ip_version: "ipv4"
          auth:
            enabled: true
            existingAdminSecret: "mongodb-admin"
          image:
            pullPolicy: "{{PULLPOLICY}}"
            repository: "{{IMAGEREPO}}"
          installImage:
            pullPolicy: "{{PULLPOLICY}}"
            repository: "{{IMAGEREPO}}"
          persistentVolume:
            accessModes:
            - ReadWriteOnce
            enabled: true
            size: "20Gi"
            storageClass: "{{STORAGECLASS}}"
          curl:
            image:
              pullPolicy: "{{PULLPOLICY}}"
              repository: "{{IMAGEREPO}}"
          replicas: "1"
          tls:
            casecret: "multicloud-ca-cert"
            issuer: "multicloud-ca-issuer"
            enabled: true
