# Copyright (c) 2024 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
appVersion: 2.12.0
description: Helm chart for the Volsync Addon Controller
name: volsync-addon-controller
keywords:
  - acm
  - volsync
  - backup
  - csi
  - data
  - disaster recovery
  - replication
  - storage
version: 1.0.0
