org: stolostron

global:
  pullPolicy: Always
  imageOverrides:
    volsync_addon_controller: ""
  templateOverrides: {}

pullSecret: null

hubconfig:
  nodeSelector: null
  replicaCount: 1
  proxyConfigs: {}
  tolerations: []
  ocpVersion: 4.12.0
