# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multiclusterhub-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multiclusterhub-role
subjects:
- kind: ServiceAccount
  name: multiclusterhub-operator
  namespace: system
