apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.clusterregistry.k8s.io
spec:
  group: clusterregistry.k8s.io
  version: v1alpha1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 10000
  versionPriority: 20
