# Copyright (c) 2022 Red Hat, Inc.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: grc-policy-addon-sa
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grc
    chart: grc-chart-{{ .Values.hubconfig.hubVersion }}
    component: "ocm-policy-addon-ctrl"
    release: grc
    app.kubernetes.io/instance: grc
    app.kubernetes.io/name: grc
