# Copyright (c) 2020 Red Hat, Inc.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grc-grc-rolebinding
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grc
    chart: grc-chart-{{ .Values.hubconfig.hubVersion }}
    component: "ocm-grc-rolebinding"
    release: grc
    app.kubernetes.io/instance: grc
    app.kubernetes.io/name: grc
roleRef:
  kind: Role
  name: grc-grc-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: grc-sa
    