apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: propagator-webhook-server-cert
  name: propagator-webhook-service
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    webhook-origin: governance-policy-propagator