# Copyright Contributors to the Open Cluster Management project

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ocm-grc-policy-propagator-metrics
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grc
    chart: grc-chart-{{ .Values.hubconfig.hubVersion }}
    component: "ocm-policy-propagator"
    release: grc
    app.kubernetes.io/instance: grc
    app.kubernetes.io/name: grc
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: https
    scheme: https
    interval: 60s
    scrapeTimeout: 10s
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: ocm-grc-policy-propagator
  namespaceSelector:
    matchNames:
    - {{ .Values.global.namespace }}
  selector:
    matchLabels:
      app: grc
      component: "ocm-policy-propagator"
      release: grc
