# Copyright (c) 2022 Red Hat, Inc.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grc-policy-addon-controller
  labels:
    app: grc
    chart: grc-chart-{{ .Values.hubconfig.hubVersion }}
    component: "ocm-policy-addon-ctrl"
    release: grc
    app.kubernetes.io/instance: grc
    app.kubernetes.io/name: grc
spec:
  replicas: {{ .Values.hubconfig.replicaCount }}
  selector:
    matchLabels:
      app: grc
      component: "ocm-policy-addon-ctrl"
      release: grc
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: grc
        ocm-antiaffinity-selector: "grcpolicyaddon"
        component: "ocm-policy-addon-ctrl"
        name: governance-policy-addon-controller
        release: grc
        chart: grc-chart-{{ .Values.hubconfig.hubVersion }}
        app.kubernetes.io/instance: grc
        app.kubernetes.io/name: grc
    spec:
      serviceAccountName: grc-policy-addon-sa
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
                - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 70
            podAffinityTerm:
              topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - grcpolicyaddon
          - weight: 35
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - grcpolicyaddon
      {{- with .Values.hubconfig.tolerations }}
      tolerations:
      {{- range . }}
      - {{ if .Key }} key: {{ .Key }} {{- end }}
        {{ if .Operator }} operator: {{ .Operator }} {{- end }}
        {{ if .Value }} value: {{ .Value }} {{- end }}
        {{ if .Effect }} effect: {{ .Effect }} {{- end }}
        {{ if .TolerationSeconds }} tolerationSeconds: {{ .TolerationSeconds }} {{- end }}
        {{- end }}
      {{- end }}  
      containers:
      - args:
        - controller
        command:
        - governance-policy-addon-controller
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CERT_POLICY_CONTROLLER_IMAGE
          value: {{ .Values.global.imageOverrides.cert_policy_controller }}
        - name: CONFIG_POLICY_CONTROLLER_IMAGE
          value: {{ .Values.global.imageOverrides.config_policy_controller }}
        - name: KUBE_RBAC_PROXY_IMAGE
          value: {{ .Values.global.imageOverrides.kube_rbac_proxy }}
        - name: GOVERNANCE_POLICY_FRAMEWORK_ADDON_IMAGE
          value: {{ .Values.global.imageOverrides.governance_policy_framework_addon }}
        image: {{ .Values.global.imageOverrides.governance_policy_addon_controller }}
        imagePullPolicy: "{{ .Values.global.pullPolicy }}"
        name: manager
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: "/tmp"
      volumes:
      - name: tmp
        emptyDir: {}
      terminationGracePeriodSeconds: 10
      {{- if .Values.global.pullSecret  }}
      imagePullSecrets:
      - name: {{ .Values.global.pullSecret  }}
      {{- end }}
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
