# Copyright (c) 2020 Red Hat, Inc.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: grc-sa
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grc
    chart: grc-chart-{{ .Values.hubconfig.hubVersion }}
    component: "ocm-grc-sa"
    release: grc
    app.kubernetes.io/instance: grc
    app.kubernetes.io/name: grc