# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ServiceAccount
metadata:
  name: insights-client
  labels:
    app: insights
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    component: insights-client
    release: {{ .Chart.Name }}
    heritage: release-service
