# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: insights-metrics-certs
  name: insights-metrics
  labels:
    insights-app: insights
    app: {{ .Chart.Name }}
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    component: insights-metrics
    release: {{ .Chart.Name }}
    heritage: release-service
spec:
  ports:
    - port: 8443 
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: {{ .Chart.Name }}
    component: "insights-metrics"
    release: {{ .Chart.Name }}
    heritage: release-service
  sessionAffinity: ClientIP
