# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: acm-insights
  namespace: {{ .Values.global.namespace }}
  labels:
    app: insights
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: insights
    heritage: release-service
    release: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Chart.Name }}'
    app.kubernetes.io/managed-by: release-service
    app.kubernetes.io/name: insights
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  endpoints:
  - interval: 60s
    port: https
    scheme: https
    scrapeTimeout: 10s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: insights-app
  selector:
    matchLabels:
      insights-app: insights
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}