global:
  hubSize: Small
  templateOverrides: {}
  imageOverrides:
    cluster_permission: ''
  namespace: open-cluster-management
  pullSecret: null
hubconfig:
  nodeSelector: null
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
  ocpVersion: 4.12.0
org: open-cluster-management
