apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multiclusterhub-operator
  namespace: default
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: multiclusterhub-operator
  source: multiclusterhub-operator-registry
  sourceNamespace: hive
  startingCSV: multiclusterhub-operator.v0.0.1
