apiVersion: v1
kind: ServiceAccount
metadata:
  name: klusterlet-addon-controller-v2
  labels:
    app: klusterlet-addon-controller-v2
    component: klusterlet-addon-controller
    app.kubernetes.io/name: klusterlet-addon-controller
