apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiclusterhub-repo
  labels:
    app: multiclusterhub-repo
spec:
  selector:
    matchLabels:
      app: multiclusterhub-repo
  replicas: 1
  template:
    metadata:
      labels:
        app: multiclusterhub-repo
    spec:
      containers:
      - name: multiclusterhub-repo
        image: multiclusterhub-repo:1.0.0
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        livenessProbe:
          httpGet:
            path: "/liveness"
            scheme: HTTP
            port: 3000
        readinessProbe:
          httpGet:
            path: "/readiness"
            scheme: HTTP
            port: 3000
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace