global:
  hubSize: Small
  imageOverrides:
    multicluster_observability_operator: ''
  namespace: default
  pullSecret: null
  templateOverrides: {}
    # Available template overrides:
    # multicluster_obs_operator_memory_request: <memory-value>
    # multicluster_obs_operator_memory_limit: <memory-value>
    # multicluster_obs_operator_cpu_request: <cpu-value>
    # multicluster_obs_operator_cpu_limit: <cpu-value>
hubconfig:
  nodeSelector: null
  ocpVersion: 4.12.0
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
