apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cert-webhook-sub
spec:
  channel: charts-v1
  name: cert-manager-webhook
  placement:
    local: true
  packageOverrides:
    - packageName: cert-manager-webhook
      packageOverrides:
      - path: spec
        value:
          imageTagPostfix: "{{SUFFIX}}"
          pkiNamespace: "{{NAMESPACE}}"
          global:
            pullSecret: "{{PULLSECRET}}"
          cainjector:
            imageTagPostfix: "{{SUFFIX}}"
            image:
              repository: "{{IMAGEREPO}}"
            serviceAccount:
              create: false
              name: default
          image:
            repository: "{{IMAGEREPO}}"
          serviceAccount:
            create: false
            name: default
