apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: app-ui-sub
spec:
  channel: charts-v1
  name: application-chart
  placement:
    local: true 
  packageOverrides:
    - packageName: application-chart 
      packageOverrides:
      - path: spec
        value:
          imageTagPostfix: "{{SUFFIX}}"
          pullSecret: "{{PULLSECRET}}"
          applicationui:
            image:
              repository: "{{IMAGEREPO}}"
              pullPolicy: "{{PULLPOLICY}}"
