kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acm-foundation
rules:
  - apiGroups: [""]
    resources: ["configmaps", "namespaces", "events", "endpoints", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "deletecollection", "patch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["get", "create"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests", "certificatesigningrequests/approval"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["signers"]
    verbs: ["approve"]
  - apiGroups: ["apps.open-cluster-management.io"]
    resources: ["deployables", "deployables/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclusters"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["action.open-cluster-management.io"]
    resources: ["managedclusteractions", "managedclusteractions/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["internal.open-cluster-management.io"]
    resources: ["managedclusterinfos", "managedclusterinfos/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["view.open-cluster-management.io"]
    resources: ["managedclusterviews", "managedclusterviews/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["proxy.open-cluster-management.io"]
    resources: ["clusterstatuses/aggregator"]
    verbs: ["get", "create"]
  - apiGroups: ["hive.openshift.io"]
    resources: ["clusterdeployments", "machinepools", "syncsets", "clusterdeployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["hive.openshift.io"]
    resources: [ "syncsets"]
    verbs: ["create", "update", "delete"]
  - apiGroups: ["inventory.open-cluster-management.io"]
    resources: ["baremetalassets", "baremetalassets/status"]
    verbs: ["get", "list", "watch", "update", "delete"]
