apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: mcm-view-aggregate
rules:
- apiGroups: ["mcm.ibm.com"]
  resources: ["resourceviews", "resourceviews/status", "works", "works/status", "worksets", "worksets/status"]
  verbs: ["create", "get", "list", "watch", "update", "delete", "deletecollection", "patch"]
- apiGroups: ["mcm.ibm.com"]
  resources: ["clusterstatuses", "helmrepos", "helmrepos/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["clusterregistry.k8s.io"]
  resources: ["clusters", "clusters/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["mcm.ibm.com"]
  resources: ["deployables", "deployables/status", "placementbindings", "placementpolicies", "placementpolicies/status", "deployableoverrides", "deployableoverrides/status", "applicationrelationships", "applicationrelationships/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps.open-cluster-management.io"]
  resources: [ "deployables", "deployables/status", "placementrules", "placementrules/status", "channels", "channels/status", "subscriptions", "subscriptions/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["app.k8s.io"]
  resources: [ "applications", "applications/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy.mcm.ibm.com"]
  resources: ["policies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["agent.open-cluster-management.io"]
  resources: ["klusterletconfigs"]
  verbs: ["get", "list"]
- apiGroups: ["hive.openshift.io"]
  resources: ["clusterdeployments", "machinepools"]
  verbs: ["get", "list"]
- apiGroups: ["config.openshift.io"]
  resources: ["clusterversions"]
  verbs: ["get", "list"]