apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    categories: A list of comma separated categories that your operator falls under.
    certified: 'false'
    containerImage: quay.io/rhibmcollab/hive:2020-04-17-ee7e42c2
    description: OpenShift cluster provisioning and management at scale.
  name: hive-operator.v0.1.1847-ee7e42c2
  namespace: hive
spec:
  customresourcedefinitions:
    owned:
    - description: Configuration for the Hive Operator
      displayName: Hive Config
      kind: HiveConfig
      name: hiveconfigs.hive.openshift.io
      version: v1
    - description: Defines an OpenShift cluster to be created.
      displayName: Cluster Deployment
      kind: ClusterDeployment
      name: clusterdeployments.hive.openshift.io
      version: v1
    - description: Defines a DNSZone to be managed in a cloud provider.
      displayName: DNS Zone
      kind: DNSZone
      name: dnszones.hive.openshift.io
      version: v1
  description: OpenShift cluster provisioning and management at scale.
  displayName: Hive
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - hive.openshift.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - velero.io
          resources:
          - backups
          verbs:
          - create
        - apiGroups:
          - ''
          resources:
          - serviceaccounts
          - serviceaccounts/finalizers
          - secrets
          - secrets/finalizers
          - services
          - services/finalizers
          - events
          - configmaps
          - namespaces
          - persistentvolumeclaims
          verbs:
          - '*'
        - apiGroups:
          - apiregistration.k8s.io
          resources:
          - apiservices
          - apiservices/finalizers
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - validatingwebhookconfigurations
          - mutatingwebhookconfigurations
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - apps
          resources:
          - deployments
          - deployments/finalizers
          - daemonsets
          - daemonsets/finalizers
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          - roles
          - rolebindings
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - authorization.openshift.io
          resources:
          - clusterroles
          - clusterrolebindings
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ''
          resources:
          - pods
          - pods/log
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - admission.hive.openshift.io
          resources:
          - dnszones
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - admission.hive.openshift.io
          resources:
          - clusterdeployments
          - clusterimagesets
          - clusterprovisions
          - dnszones
          - machinepools
          - selectorsyncsets
          - syncsets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        serviceAccountName: hive-operator
      deployments:
      - name: hive-operator
        spec:
          replicas: 1
          revisionHistoryLimit: 4
          selector:
            matchLabels:
              control-plane: hive-operator
              controller-tools.k8s.io: '1.0'
          template:
            metadata:
              labels:
                control-plane: hive-operator
                controller-tools.k8s.io: '1.0'
            spec:
              containers:
              - command:
                - /opt/services/hive-operator
                - --log-level
                - info
                env:
                - name: CLI_CACHE_DIR
                  value: /var/cache/kubectl
                - name: HIVE_OPERATOR_NS
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/rhibmcollab/hive:2020-04-08-520125dc
                imagePullPolicy: Always
                livenessProbe:
                  failureThreshold: 1
                  httpGet:
                    path: /debug/health
                    port: 8080
                  initialDelaySeconds: 10
                  periodSeconds: 10
                name: hive-operator
                resources:
                  requests:
                    cpu: 100m
                    memory: 256Mi
                volumeMounts:
                - mountPath: /var/cache/kubectl
                  name: kubectl-cache
              serviceAccountName: hive-operator
              terminationGracePeriodSeconds: 10
              volumes:
              - emptyDir: {}
                name: kubectl-cache
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - kubernetes
  - openshift
  - multi-cluster
  - cluster
  maturity: alpha
  provider:
    name: Red Hat, Inc
  version: 0.1.1847-ee7e42c2
