# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: "open-cluster-management:multicloud-operators-subscription:rbac-aggregate-view"
rules:
- apiGroups:
  - app.k8s.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - channels
  - deployables
  - gitopsclusters
  - helmreleases
  - placementrules
  - subscriptionreports
  - subscriptions
  - subscriptionstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - applications.app.k8s.io
  - channels.apps.open-cluster-management.io
  - deployables.apps.open-cluster-management.io
  - gitopsclusters.apps.open-cluster-management.io
  - helmreleases.apps.open-cluster-management.io
  - placementrules.apps.open-cluster-management.io
  - subscriptionreports.apps.open-cluster-management.io
  - subscriptions.apps.open-cluster-management.io
  - subscriptionstatuses.apps.open-cluster-management.io
  resources:
  - customresourcedefinitions
  verbs:
  - get