# Copyright (c) 2020 Red Hat, Inc.

global:
  imageOverrides:
    governance_policy_propagator: ""
    governance_policy_addon_controller: ""
    cert_policy_controller: ""
    iam_policy_controller: ""
    config_policy_controller: ""
    governance_policy_spec_sync: ""
    governance_policy_status_sync: ""
    governance_policy_template_sync: ""
    kube_rbac_proxy: ""
  namespace: default
  pullSecret: null
  pullPolicy: Always
hubconfig:
  nodeSelector: null
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
