apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: etcd-cluster
  namespace: multicluster-system
spec:
  size: 3
  version: 3.2.13
  pod:
    persistentVolumeClaimSpec:
      storageClassName: "{{STORAGECLASS}}"
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi