# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
appVersion: 2.12.0
category: "Development"
description: Helm chart for Open Cluster Management Console
keywords:
  - ui
kubeVersion: ">=1.10.0-0"
name: console-chart
version: 2.12.0
