# Default values for console-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

org: open-cluster-management

global:
  imageOverrides:
    console: ""
  namespace: default
  pullSecret: null
  imageRepository: "" # utils.GetImageRepository(m)
hubconfig:
  nodeSelector: null
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []




global:
  imageOverrides:
    console: ""
    pullPolicy: Always

pullSecret: null
arch:
- amd64
- ppc64le
- s390x
- arm64

ocpingress: ""

hubconfig:
  nodeSelector: null
  replicaCount: 1
  ocpVersion: "4.6.0"
  tolerations:
    - key: dedicated
      operator: Exists
      effect: NoSchedule
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists

console:
  resources:
    requests:
      memory: "40Mi"
      cpu: "3m"

clusterImageSets:
  subscriptionPause: "false"
  acmHiveOpenshiftReleaseUrl: "https://github.com/stolostron/acm-hive-openshift-releases.git"
