- repo_name: search-v2-operator
  github_ref: "https://github.com/stolostron/search-v2-operator.git"
  branch: "release-2.6"
  operators:
    - name: search-v2-operator
      bundlePath: "bundle/manifests/"
      imageMappings:
        search-v2-operator: search_v2_operator 
        kube-rbac-proxy: kube_rbac_proxy
        postgresql-13: postgresql_12
        search-indexer: search_indexer
        search-collector: search_collector
        search-v2-api: search_v2_api
