# Copyright Contributors to the Open Cluster Management project


resources:
- clusterrole-admin-aggregate.yaml
- clusterrole-edit-aggregate.yaml
- clusterrole-view-aggregate.yaml
- clusterrole-clustermanageradmin.yaml
- clusterrole-clustermanageradmin-aggregate.yaml
