apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ .Values.org }}:{{ .Chart.Name }}:multicluster-observability-operator'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ .Values.org }}:{{ .Chart.Name }}:multicluster-observability-operator'
subjects:
- kind: ServiceAccount
  name: multicluster-observability-operator
  namespace: '{{ .Values.global.namespace }}'
