name: Installer Function Tests (Mock Image)

on: 
  # Trigger when PR is submitted to main
  pull_request:
    branches:
      - main
      - add-pull-request-function-tests #Testing only

  # manual trigger
  workflow_dispatch:

jobs:
  function-test:
    runs-on: ubuntu-latest
    steps:
      - uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: ${{ secrets.FF_TOKEN }}
          valid-labels: ok-to-test
          
      - uses: actions/checkout@v2

      - name: Run Function Tests
        run: |
          echo "Running Pull Request Function Tests ..."
          ./common/scripts/pull-request-function-test.sh
        env:
          COLLECTIVE_TOKEN: ${secrets.COLLECTIVE_TOKEN}
